In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\mishr\\Documents\\Python\\Datasets\\Zomato Dataset.csv")

In [2]:
print(df)

           ID Delivery_person_ID  Delivery_person_Age  \
0      0xcdcd      DEHRES17DEL01                 36.0
1      0xd987      KOCRES16DEL01                 21.0
2      0x2784     PUNERES13DEL03                 23.0
3      0xc8b6     LUDHRES15DEL02                 34.0
4      0xdb64      KNPRES14DEL02                 24.0
...       ...                ...                  ...
45579  0x7c09      JAPRES04DEL01                 30.0
45580  0xd641      AGRRES16DEL01                 21.0
45581  0x4f8d     CHENRES08DEL03                 30.0
45582  0x5eee    COIMBRES11DEL01                 20.0
45583  0x5fb2   RANCHIRES09DEL02                 23.0

       Delivery_person_Ratings  Restaurant_latitude  Restaurant_longitude  \
0                          4.2            30.327968             78.046106
1                          4.7            10.003064             76.307589
2                          4.7            18.562450             73.916619
3                          4.3            30.899584             75.809346
4                          4.7            26.463504             80.372929
...                        ...                  ...                   ...
45579                      4.8            26.902328             75.794257
45580                      4.6             0.000000              0.000000
45581                      4.9            13.022394             80.242439
45582                      4.7            11.001753             76.986241
45583                      4.9            23.351058             85.325731

       Delivery_location_latitude  Delivery_location_longitude  Order_Date  \
0                       30.397968                    78.116106  12-02-2022
1                       10.043064                    76.347589  13-02-2022
2                       18.652450                    74.006619  04-03-2022
3                       30.919584                    75.829346  13-02-2022
4                       26.593504                    80.502929  14-02-2022
...                           ...                          ...         ...
45579                   26.912328                    75.804257  24-03-2022
45580                    0.070000                     0.070000  16-02-2022
45581                   13.052394                    80.272439  11-03-2022
45582                   11.041753                    77.026241  07-03-2022
45583                   23.431058                    85.405731  02-03-2022

      Time_Orderd Time_Order_picked Weather_conditions Road_traffic_density  \
0           21:55             22:10                Fog                  Jam
1           14:55             15:05             Stormy                 High
2           17:30             17:40         Sandstorms               Medium
3           09:20             09:30         Sandstorms                  Low
4           19:50             20:05                Fog                  Jam
...           ...               ...                ...                  ...
45579       11:35             11:45              Windy                 High
45580       19:55             20:10              Windy                  Jam
45581       23:50          24:05:00             Cloudy                  Low
45582       13:35             13:40             Cloudy                 High
45583       17:10             17:15                Fog               Medium

       Vehicle_condition Type_of_order Type_of_vehicle  multiple_deliveries  \
0                      2         Snack      motorcycle                  3.0
1                      1          Meal      motorcycle                  1.0
2                      1        Drinks         scooter                  1.0
3                      0        Buffet      motorcycle                  0.0
4                      1         Snack         scooter                  1.0
...                  ...           ...             ...                  ...
45579                  1          Meal      motorcycle                  0.0
45580                  0        Buffet      motorcycle                  1.0
45581                  1        Drinks         scooter                  0.0
45582                  0         Snack      motorcycle                  1.0
45583                  2         Snack         scooter                  1.0

      Festival           City  Time_taken (min)
0           No  Metropolitian                46
1           No  Metropolitian                23
2           No  Metropolitian                21
3           No  Metropolitian                20
4           No  Metropolitian                41
...        ...            ...               ...
45579       No  Metropolitian                32
45580       No  Metropolitian                36
45581       No  Metropolitian                16
45582       No  Metropolitian                26
45583       No  Metropolitian                36

[45584 rows x 20 columns]

In [3]:
df['City_Initial']= df['Delivery_person_ID'].str[:3]

In [4]:
df['City_Initial']

0        DEH
1        KOC
2        PUN
3        LUD
4        KNP
        ...
45579    JAP
45580    AGR
45581    CHE
45582    COI
45583    RAN
Name: City_Initial, Length: 45584, dtype: object

In [5]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),City_Initial
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,...,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,DEH
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,...,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,KOC
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,...,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,PUN
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,...,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,LUD
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,...,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,KNP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,...,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32,JAP
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,...,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36,AGR
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,...,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,CHE
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,...,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26,COI
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,...,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36,RAN

In [17]:
df['Order_Date']= pd.to_datetime(df['Order_Date'], format= 'mixed')

In [18]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),City_Initial
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-12-02,21:55,...,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,DEH
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,14:55,...,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,KOC
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-04-03,17:30,...,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,PUN
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,09:20,...,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,LUD
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,19:50,...,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,KNP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35,...,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32,JAP
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55,...,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36,AGR
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-11-03,23:50,...,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,CHE
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-07-03,13:35,...,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26,COI
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-02-03,17:10,...,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36,RAN

In [19]:
df['Delivery_ID'] = df['Delivery_person_ID'].str[4:]

In [20]:
df.Delivery_ID

0           ES17DEL01
1           ES16DEL01
2          RES13DEL03
3          RES15DEL02
4           ES14DEL02
             ...
45579       ES04DEL01
45580       ES16DEL01
45581      RES08DEL03
45582     BRES11DEL01
45583    HIRES09DEL02
Name: Delivery_ID, Length: 45584, dtype: object

In [21]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),City_Initial,Delivery_ID
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-12-02,21:55,...,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,DEH,ES17DEL01
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,14:55,...,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,KOC,ES16DEL01
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-04-03,17:30,...,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,PUN,RES13DEL03
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,09:20,...,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,LUD,RES15DEL02
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,19:50,...,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,KNP,ES14DEL02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35,...,High,1,Meal,motorcycle,0.0,No,Metropolitian,32,JAP,ES04DEL01
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55,...,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36,AGR,ES16DEL01
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-11-03,23:50,...,Low,1,Drinks,scooter,0.0,No,Metropolitian,16,CHE,RES08DEL03
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-07-03,13:35,...,High,0,Snack,motorcycle,1.0,No,Metropolitian,26,COI,BRES11DEL01
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-02-03,17:10,...,Medium,2,Snack,scooter,1.0,No,Metropolitian,36,RAN,HIRES09DEL02

In [23]:
df.to_csv ("C:\\Users\\mishr\\Documents\\Python\\Datasets\\Zomato_Dataset_1.csv")